version: "3"

services:
  app:
    container_name: next_app

    build:
      context: . # ビルドに必要なファイルが存在するディレクトリのパスを指定
      dockerfile: Dockerfile.dev # ビルドに使用するDockerfileの名前を指定

    volumes:
      # ホストのディレクトリとコンテナの/workspaceをマウント
      - node_modules:/workspace/node_modules
      - ./:/workspace:cached
      - type: bind
        source: ~/.ssh
        target: /home/node/.ssh

    entrypoint: "/bin/sh -c 'npm run dev'"

    ports:
      - 127.0.0.1:3000:3000 # ホストのポート3000をコンテナのポート3000にマッピング

    networks:
      - next_app_network # コンテナが参加するネットワークの名前

volumes:
  node_modules:
    name: next_app_node_modules

networks:
  next_app_network:
    driver: bridge