FROM node:22-alpine

WORKDIR /workspace

RUN apk update && apk add --no-cache \
    openssh \
    git \
    bash \
    && rm -rf /var/cache/apk/*

RUN mkdir -p /workspace/node_modules

# 依存関係をインストール
COPY package.json package-lock.json ./

RUN npm install

RUN chown -R node:node ./
USER node

# Next.jsによってテレメトリデータを収集するのを無効にする
ARG NEXT_TELEMETRY_DISABLED=1
ENV NEXT_TELEMETRY_DISABLED=$NEXT_TELEMETRY_DISABLED

# git関係のセットアップ
RUN git config --global --add safe.directory /workspaces/k256

# 注意: ポートのマッピングはdocker-composeで行うため、設定しない

# CMD ["npm", "run", "dev"]