name: Docker Build and Deploy to Artifact Registry

on:
  push:
    branches:
      - main
      
jobs:
  build-and-deploy:
    name: Setup, Build, Publish, and Deploy.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      # 3. Artifact Registry への Docker 認証設定
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-docker.pkg.dev

      # 4. Docker Compose を使用してビルド
      - name: Build Docker image with Docker Compose
        run: |
          docker compose -f docker-compose.yml build

      # 5. Docker Compose を使用してタグ付けしてプッシュ
      - name: Tag and push Docker images
        run: |
          docker tag k256-next_app:latest us-docker.pkg.dev/third-technique-387000/portfolio-repo/portfolio-image:latest
          docker push us-docker.pkg.dev/third-technique-387000/portfolio-repo/portfolio-image:latest

      # 6. DockerイメージをGCE上で動かす
      - name: ssh and deploy
        uses: appleboy/ssh-action@master # １
        with: 
          host: ${{ secrets.SSH_HOST }} # ホスト名
          username: ${{ secrets.SSH_USERNAME }} # SSH ユーザ名
          key: ${{ secrets.SSH_PRIVATE_KEY }} # 秘密鍵の内容
          port: ${{ secrets.SSH_PORT }} # ポート番号
          passphrase: ${{ secrets.SSH_PASSPHRASE }} # パスフレーズ
          debug: true
          script: |
            docker stop portfolio-container
            docker rm portfolio-container
            docker pull us-docker.pkg.dev/third-technique-387000/portfolio-repo/portfolio-image:latest
            docker run -d -p ${{ secrets.PORT }}:${{ secrets.PORT }} --name portfolio-container us-docker.pkg.dev/third-technique-387000/portfolio-repo/portfolio-image:latest
