name: Docker Build and Deploy to Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # リポジトリのコードをチェックアウト
    - name: Checkout code
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    # Dockerの設定
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Dockerイメージをビルド
    - name: Build Docker image
      run: |
        docker build -t us-docker.pkg.dev/third-technique-387000/portfolio-repo/portfolio-image:$GITHUB_SHA .

    # DockerイメージをArtifact Registryにプッシュ
    - name: Push Docker image to Artifact Registry
      run: |
        docker push us-docker.pkg.dev/third-technique-387000/portfolio-repo/portfolio-image:$GITHUB_SHA
