name: Docker Build and Deploy to Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # リポジトリのコードをチェックアウト
    - name: Checkout code
      uses: actions/checkout@v2

    # GCP認証
    - name: Set up Google Cloud authentication
      uses: google-github-actions/setup-gcloud@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: third-technique-387000

    # Dockerの設定
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Dockerイメージをビルド
    - name: Build Docker image
      run: |
        docker build -t us-docker.pkg.dev/third-technique-387000/portfolio-repo/portfolio-image:$GITHUB_SHA .

    # DockerイメージをArtifact Registryにプッシュ
    - name: Push Docker image to Artifact Registry
      run: |
        docker push us-docker.pkg.dev/third-technique-387000/portfolio-repo/portfolio-image:$GITHUB_SHA
