name: Docker Build and Deploy to Artifact Registry

on:
  push:
    branches:
      - main
      
jobs:
  build-and-deploy:
    name: Setup, Build, Publish, and Deploy.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: 'auth'
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${GCP_SA_KEY}'

      # Dockerの設定
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Dockerイメージをビルド
      - name: Build Docker image
        run: |
          docker build -t us-docker.pkg.dev/third-technique-387000/portfolio-repo/portfolio-image:$GITHUB_SHA .

      # DockerイメージをArtifact Registryにプッシュ
      - name: Push Docker image to Artifact Registry
        run: |
          docker push us-docker.pkg.dev/third-technique-387000/portfolio-repo/portfolio-image:$GITHUB_SHA
